### ISSUE TITLE
Ability to use a post-command and post

### ISSUE THREAD

**Issue by lcharleux** [elmokulc/conman#1]
It would be appreciated to be able to define a script for post-create and post-start commands instead of one-line command.

**Comment by elmokulc** [comment]
Thank you for your suggestion,

This ability have been incorporate from release 1.1.5 ([see](https://github.com/elmokulc/conman/commit/3d48e4f0d9521b945fe4434e620d830b8f97d3b6#commitcomment-133299078)).
